=== free-domains/register/schemas/domain.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "description": "Path to the schema file"
        },
        "domain": {
            "type": "string",
            "enum": ["is-a-backend.dev", "is-a-frontend.dev"]
        },
        "subdomain": {
            "type": "string",
            "pattern": "^([a-z0-9_*.-]{1,63}|@)$"
        },
        "owner": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "email": {
                    "type": "string",
                    "description": "Email Address"
                }
            }
        },
        "records": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "A": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "minProperties": 2,
                        "maxProperties": 2
                    }
                },
                "AAAA": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "minProperties": 2,
                        "maxProperties": 2
                    }
                },
                "CNAME": {
                    "type": "object",
                    "minProperties": 2,
                    "maxProperties": 2
                },
                "TXT": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "minProperties": 2,
                        "maxProperties": 2
                    }
                }
            },
            "anyOf": [
                { "required": ["A"] },
                { "required": ["AAAA"] },
                { "required": ["CNAME"] },
                { "required": ["TXT"] }
            ]
        }
    },
    "required": ["$schema", "domain", "subdomain", "owner", "records"]
}

=== free-domains/register/domains/anish.is-a-frontend.dev.json
{
    "$schema": "../schemas/domain.json",

    "domain": "is-a-frontend.dev",
    "subdomain": "anish",

    "owner": {
        "email": "anishn0509@gmail.com"
    },

    "records": {
        "CNAME": {
            "value": "anishnarayan1.github.io.",
            "proxied": false
        },

        "TXT": [
            {
                "name": "_github-pages-challenge-AnishNarayan1",
                "value": "48401d78e76c51bfa3b976e72c2b3b"
            }
        ]
    }
}
